-- 统一任务模型：入口规划和执行单元均为 async_task，通过 parent_task_id 构成任务树。
-- 当前版本不保留历史任务；任务协议与 API 均为破坏性变更。
DROP TABLE public.async_task;
DROP TABLE public.task_submission;

CREATE TABLE public.async_task
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_task_id   BIGINT REFERENCES public.async_task (id) ON DELETE RESTRICT,
    namespace        TEXT        NOT NULL,
    task_type        TEXT        NOT NULL,
    action            TEXT        NOT NULL,
    payload           JSONB       NOT NULL,
    status            TEXT        NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    completed_reason TEXT,

    CONSTRAINT ck_async_task_action
        CHECK (action IN ('PLAN', 'RUN')),
    CONSTRAINT ck_async_task_payload_object
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_async_task_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX idx_async_task_discovery
    ON public.async_task (status, namespace, task_type);

CREATE INDEX idx_async_task_claim
    ON public.async_task (namespace, task_type, status, created_at, id);

CREATE INDEX idx_async_task_parent
    ON public.async_task (parent_task_id, created_at, id);

CREATE UNIQUE INDEX uq_async_task_active_child
    ON public.async_task (
        parent_task_id,
        namespace,
        task_type,
        action,
        sha256(jsonb_send(payload))
    )
    WHERE parent_task_id IS NOT NULL AND status IN ('PENDING', 'RUNNING');
