-- 插件任务架构：任务身份改为 (namespace, task_type) 二元组，
-- 引入 task_submission 规划资源并重建 async_task 与 plugin。
-- 破坏性升级：直接删除全部旧任务记录与已安装插件，不做数据转换。

DROP TABLE public.async_task_log;
DROP TABLE public.plugin;

CREATE TABLE public.plugin
(
    id              TEXT        PRIMARY KEY,
    name            TEXT,
    version         TEXT        NOT NULL,
    abi             TEXT        NOT NULL,
    task_type       TEXT        NOT NULL,
    concurrency     INTEGER     NOT NULL,
    form_definition JSONB       NOT NULL,
    wasm            BYTEA       NOT NULL,
    enabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_plugin_id_reserved
        CHECK (id NOT LIKE 'app.unirhy%'),
    CONSTRAINT ck_plugin_concurrency_positive
        CHECK (concurrency > 0),
    CONSTRAINT ck_plugin_form_definition
        CHECK (
            jsonb_typeof(form_definition) = 'object'
            AND form_definition ? 'schema'
            AND jsonb_typeof(form_definition -> 'schema') = 'object'
            AND form_definition ? 'order'
            AND jsonb_typeof(form_definition -> 'order') = 'array'
        ),
    CONSTRAINT ck_plugin_updated_at
        CHECK (updated_at >= created_at)
);

CREATE TABLE public.task_submission
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace        TEXT        NOT NULL,
    task_type        TEXT        NOT NULL,
    params           JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    completed_reason TEXT,

    CONSTRAINT ck_task_submission_params_object
        CHECK (jsonb_typeof(params) = 'object'),
    CONSTRAINT ck_task_submission_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX idx_task_submission_discovery
    ON public.task_submission (status, namespace, task_type);

CREATE INDEX idx_task_submission_claim
    ON public.task_submission (namespace, task_type, status, created_at, id);

CREATE TABLE public.async_task
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id    BIGINT      NOT NULL
        REFERENCES public.task_submission (id) ON DELETE CASCADE,
    namespace        TEXT        NOT NULL,
    task_type        TEXT        NOT NULL,
    payload          JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    completed_reason TEXT,

    CONSTRAINT ck_async_task_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX idx_async_task_discovery
    ON public.async_task (status, namespace, task_type);

CREATE INDEX idx_async_task_claim
    ON public.async_task (namespace, task_type, status, created_at, id);

CREATE INDEX idx_async_task_submission
    ON public.async_task (submission_id, created_at, id)
    INCLUDE (status);

CREATE UNIQUE INDEX uq_async_task_active_payload
    ON public.async_task (
        namespace,
        task_type,
        sha256(jsonb_send(payload))
    )
    WHERE status IN ('PENDING', 'RUNNING');
